version: 2
build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
python:
  install:
  - method: pip
    path: docs/
    extra_requirements:
    - diracdoctools
conda:
  environment: environment-py3.yml
formats: []
