name: Python 3 tests

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.repository == 'DIRACGrid/DIRAC'
    timeout-minutes: 30
    defaults:
      # Activate the conda environment automatically in each step
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: False
      matrix:
        command:
          # TODO These three tests fail on Python 3:
          #   * `test_BaseType_Unicode` and `test_nestedStructure` fail due to
          #     DISET's string and unicode types being poorly defined
          #   * `testLockedClass` deadlocks frequently due to the use of
          #     self.__processThread._Thread__stop(). Officially "threads
          #     cannot be destroyed, stopped, suspended, resumed, or
          #     interrupted" so the code should be rewritten to follow the
          #     supported alternative: "If you want your threads to stop
          #     gracefully, make them non-daemonic and use a suitable
          #     signalling mechanism such as an Event."
          - pytest --runslow -k 'not test_BaseType_Unicode and not test_nestedStructure and not testLockedClass'
          - pylint -E src/

    steps:
    - uses: actions/checkout@v2
    - name: Fail-fast for outdated pipelines
      run: .github/workflows/fail-fast.sh
    - uses: conda-incubator/setup-miniconda@master
      with:
        environment-file: environment-py3.yml
        miniforge-variant: Mambaforge
        use-mamba: true
    - name: Run tests
      run: |
        # FIXME: The unit tests currently only work with editable installs
        pip install -e .[server,testing]
        ${{ matrix.command }}
      env:
        REFERENCE_BRANCH: ${{ github['base_ref'] || github['head_ref'] }}
